name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari
  workflow_dispatch:      # bisa dijalankan manual juga

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: 4zizie
          outputs: dist

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
